version: '3'
services:

  mongodb:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - db-data:/data/db

  mongo-express:
    image: mongo-express
    depends_on:
     - mongodb
    restart: unless-stopped
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password@mongodb:27017/

  portfolio-app:
    image: arriba87/portfolio-app
    depends_on:
     - mongodb
    restart: unless-stopped
    ports:
      - 8050:8050
    environment:
      - MONGO_DB_USERNAME=admin
      - MONGO_DB_PWD=password
      - NEWSAPI_KEY=*
    
volumes:
  db-data:
    driver: local


