@startuml
title "App Interaction"

left to right direction

actor "User" as user

rectangle FrontEnd {
    usecase "SELECT portfolio" as select
    usecase "EDIT portfolio" as edit
    usecase "DELETE portfolio" as delete
    usecase "visualization:\n/overview\n/allocation\n/forecast" as visualize
}

actor "PortfolioDB" as App

database "MongoDB" as db

user --> select
user --> edit
user --> delete
user --> visualize

select --> App
edit --> App
delete --> App

App <--> db : "get_portfolio()"
App --> db : "store_new_portfolio()"
App --> db : "delete_portfolio()"

App --> visualize

@enduml